// Quadratic Formula Calculator

#include <iostream>
#include <cmath>
#include <cstdlib>
#include <iomanip>

using namespace std;

void getInput(double &a, double &b, double &c);
// Gets user input to determine the coefficients of
// each of the terms in the quadratic equation.

void printRoots(double a, double b, double c);
// Uses the quadratic formula to calculate the roots
// of the quadratic equation generated by the user input
// coefficients. Checks for real an imaginary roots and
// outputs appropriate result (i.e. with imaginary component
// distinct from real component).

struct Root
{
    double real;
    double imaginary;
};

int main()
{
    cout.setf(ios::fixed);
    cout.setf(ios::showpoint);
    cout.precision(4);

    double a = 0.0;
    double b = 0.0;
    double c = 0.0;

    cout << "*****************************" << endl;
    cout << "Quadratic Formula Calculator!" << endl;
    cout << "*****************************" << endl << endl << endl;

    getInput(a, b, c);
    printRoots(a, b, c);
    cout << endl;
    system("pause");
    return 0;
}

void getInput(double &a, double &b, double &c)
{
    cout << "Please enter a value for the coefficient of the first term (a)\n"
         << "and press return: ";
    cin >> a;
    cout << endl;
    cout << "The value of a entered is: " << a << "."<< endl << endl;

    cout << "Please enter a value for the coefficient of the second term (b)\n"
         << "and press return: ";
    cin >> b;
    cout << endl;
    cout << "The value of b entered is: " << b << "."<< endl << endl;

    cout << "Please enter a value for the last term (c)\n"
         << "and press return: ";
    cin >> c;
    cout << endl;
    cout << "The value of c entered is: " << c << "."<< endl << endl;

}

void printRoots(double a, double b, double c)
{
    cout << "The roots of the quadratic with terms: \n"
         << "a = " << a << ", " << "b = " << b << "c = " << c << " are:" << endl << endl;

    if (pow(b, 2) - 4*a*c < 0)
    {
        Root root;

        root.real = (-1 * b) / (2 * a);
        root.imaginary = sqrt(fabs(pow(b, 2) - 4*a*c)) / (2 * a);

        cout << "Root 1 is: " << root.real << " + " << root.imaginary << "i" << endl;
        cout << "Root 2 is: " << root.real << " - " << root.imaginary << "i" << endl;
    }

    else
    {
        Root root1;
        Root root2;

        root1.real = ((-1 * b) + sqrt(pow(b, 2) - 4*a*c)) / (2 * a);
        root2.real = ((-1 * b) - sqrt(pow(b, 2) - 4*a*c)) / (2 * a);

        cout << "Root 1 is: " << root1.real << endl;
        cout << "Root 2 is: " << root2.real << endl;
    }


}
